nelmio_cors:
    defaults:
        allow_origin: ['http://www.localhost:8000'] # Remplacez ceci par l'URL de votre application front-end
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
        allow_headers: ['Content-Type']
        max_age: 3600
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/': # Configurez cette partie en fonction de vos routes backend
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600
            # expose_headers: ['Link']
            # allow_credentials: true
